apiVersion: v1
kind: PersistentVolume
metadata:
  name: user-db2-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""   
  hostPath:              
    path: /mnt/sqlite-user-db
    type: DirectoryOrCreate
