apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlite-data-user-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: user-db2-pv   # bind to this PV
  storageClassName: ""       # must match PV
